### ISSUE TITLE
Script  Doesn't executes completely 

### ISSUE THREAD

**Issue by punjabishaw** [AbsorbingChaos/bks-setup-miner#44]
![image](https://user-images.githubusercontent.com/37134001/102271093-e5c2b180-3f44-11eb-8a03-72defa159be3.png)

**Comment by whoabuddy** [comment]
Thanks for reporting! I had a similar issue recently and I think it's related to trying to pull an older version of the repo via tags. 

Once I get this replicated and fixed on my own miner I'll upload something here.

**Comment by HaroldDavis3** [comment]
This happened to me earlier in the day but fixed itself on restart. Ty kindly for the updates @whoabuddy; miner has been up all day!

**Comment by whoabuddy** [comment]
Fixed in #45
